### PR TITLE
Add translation for and and friends

### PR DESCRIPTION
**Pull request by WebSnke**
This PR will add translation for "and" and "friends".

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensourcefriday/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by WebSnke** [comment]
> Please add back in, and fill out, the PR template. Thank you.

I can't find the template right now. Can you send me a link to it?

**Comment by kenyonj** [comment]
> I can't find the template right now. Can you send me a link to it?

Apologies, I expected them to be there, but they weren't. I just added them to the repository and I will add them to the PR body now for you to fill out.

Thanks!

**Comment by WebSnke** [comment]
> > I can't find the template right now. Can you send me a link to it?
> 
> Apologies, I expected them to be there, but they weren't. I just added them to the repository and I will add them to the PR body now for you to fill out.
> 
> Thanks!

I just filled it out.

**Review by kenyonj — APPROVED** [review]

**Comment by kenyonj** [comment]
Looks great. Thanks for your contribution!

**Pull request merged**
